#!/usr/bin/env bash
# Script that displays information about subdomains of a given domain

get_subdomain_info() {
    local domain="$1"
    local subdomain="$2"
    local info
    local record_type
    local destination

    info=$(dig "${subdomain}.${domain}" | awk '/ANSWER SECTION:/{getline; print $4, $5}')
    record_type=$(echo $info | awk '{print $1}')
    destination=$(echo $info | awk '{print $2}')

    echo "The subdomain ${subdomain} is a ${record_type} record and points to ${destination}"
}

domain="$1"
subdomain="$2"

if [ -z "$subdomain" ]; then
    get_subdomain_info "$domain" "www"
    get_subdomain_info "$domain" "lb-01"
    get_subdomain_info "$domain" "web-01"
    get_subdomain_info "$domain" "web-02"
else
    get_subdomain_info "$domain" "$subdomain"
fi
