#!/usr/bin/env bash
# Script that displays information about subdomains of a given domain

get_subdomain_info() {
    local domain="$1"
    local subdomain="$2"
    local record_type
    local destination

    record_type=$(dig +noall +answer "${subdomain}.${domain}" | awk '{print $4}')
    destination=$(dig +noall +answer "${subdomain}.${domain}" | awk '{print $5}')

    echo "The subdomain ${subdomain} is a ${record_type} record and points to ${destination}"
}

domain="$1"
subdomain="$2"

if [ -z "$subdomain" ]; then
    get_subdomain_info "$domain" "www"
    get_subdomain_info "$domain" "lb-01"
    get_subdomain_info "$domain" "web-01"
    get_subdomain_info "$domain" "web-02"
else
    get_subdomain_info "$domain" "$subdomain"
fi
