#!/usr/bin/env bash
# Script that displays information about subdomains of a given domain

get_subdomain_info() {
    local domain="$1"
    local subdomain="$2"
    local result
    local record_type
    local destination

    result=$(dig +noall +answer "${subdomain}.${domain}" | awk '$4=="A" {print $4, $5; exit}')
    record_type=$(echo $result | awk '{print $1}')
    destination=$(echo $result | awk '{print $2}')

    echo "The subdomain ${subdomain} is a ${record_type} record and points to ${destination}"
}

domain="$1"
subdomain="$2"

if [ -z "$subdomain" ]; then
    get_subdomain_info "$domain" "www"
    get_subdomain_info "$domain" "lb-01"
    get_subdomain_info "$domain" "web-01"
    get_subdomain_info "$domain" "web-02"
else
    get_subdomain_info "$domain" "$subdomain"
fi
